config/routes.rb
ThisOrThat::Application.routes.draw do |map|
  resources :polls do
    resources :votes
  end

  root :to => "polls#index"
end

app/models/poll.rb
class Poll < ActiveRecord::Base
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  # protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  expose(:poll) { Poll.first }

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  expose(:poll) { Poll.find_by_id(params[:poll_id]) }

  def create
    Poll.increment_counter(
      params[:choice] == 'bohemian' ? :bohemian : :stairway,
      params[:poll_id]
    )
    redirect_to poll_path(poll)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper

  def graph_height(poll, choice)
    total = poll.bohemian + poll.stairway
    "height: #{((poll.send(choice).to_f / total.to_f)*100).to_i}%"
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Stairway or Bohemian
    = stylesheet_link_tag 'styles'
    = javascript_include_tag 'jquery-1.4.2.min', 'rails'
  %body
    #wrapper= yield
    #footer
      An indescribably valuable survey of the human race brought to you by Cameron and Paul

app/views/polls/ie.haml
#ie
  %h1
    Dear Sir or Madam,
  %p
    As we detect that you are using Internet Explorer, 
    your judgment is in question
    AND YOU DO NOT GET TO VOTE
  %p
    %a(href="#") Click here to download a proper Internet Browser

app/views/polls/index.haml
#choice
  - link_to poll_votes_path(poll, :choice => 'stairway'), :method => 'post' do
    %span STAIRWAY TO HEAVEN
  .or
    %span or
  - link_to poll_votes_path(poll, :choice => 'bohemian'), :method => 'post' do
    %span BOHEMIAN RHAPSODY

app/views/polls/show.html.haml
#results 
  %h1 Thank you for your vote
  %h2 Here are the results so far
  #graph
    .result
      %span{:style => graph_height(poll, :stairway)}= poll.stairway
      Stairway
    .result
      %span{:style => graph_height(poll, :bohemian)}= poll.bohemian
      Bohemian
  %p Thank you for participating in this essential study.
  %p Soon, so very soon, the great question will be answered once and for all.